apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU= #base64 encoded
    mongo-root-password: cGFzc3dvcmQ= #base64 encoded
    mongo-express-username: dXNlcm5hbWU= #base64 encoded
    mongo-express-password: byY3MTBicHhZN0ZBRDh0dHhPMnE= #base64 encoded
